version: "3"

services:
  postgres_db:
    image: 'postgres:14'
    container_name: 'test_task_postgres_db'
    restart: always
    volumes:
      - ./src/main/resources/tmp/postgres:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=test'
    ports:
      - '54223:5432'
