server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    edu.rd.spcity: DEBUG

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: root

  liquibase:
    url: jdbc:postgresql://localhost:5432/test
    user: postgres
    password: root
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    properties:

      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        ddl.auto: none
        show_sql: true
        format_sql: false
    open-in-view: false

url:
  api:
    version: v0
